workflows:
  build:
    name: Build
    instance_type: mac_pro
    max_build_duration: 60
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
    cache:
      cache_paths:
        - /Users/builder/clone/Modules/Lib1/Pods
        - /Users/builder/clone/Modules/Lib1/Podfile.lock
    scripts:
      - name: Install Cocoapods Dependencies
        working_directory: Modules/Lib1
        script: pod install
      - name: Xcode Build
        working_directory: Modules/Lib1
        script: xcodebuild build -workspace 'Lib1.xcworkspace' -scheme 'SandboxApp' -sdk 'iphonesimulator'
