workflows:
  build:
    name: Build
    instance_type: mac_pro
    max_build_duration: 60
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
    cache:
      cache_paths:
        - ~/Modules/Lib1/Pods/
        - ~/Modules/Lib1/Podfile.lock
    scripts:
      - cd Modules/Lib1 && pod install
      - xcodebuild build -workspace 'Lib1.xcworkspace' -scheme 'SandboxApp' -sdk 'iphonesimulator'
